architecture:
  conv_layers:
    - [32, 64, 128, 256]
    - [64, 128, 256, 512]
  kernel_size: [3, 4]
  stride: [1, 2]
  padding: [0, 1]
  use_batch_norm: [true, false]
  use_group_norm: [true, false]
  use_instance_norm: [true, false]
  use_min_max_scaling: [true, false]
  activation_conv: ["relu", "leaky_relu", "prelu", "gelu", "swish"]
  weight_initialization: ["xavier", "kaiming", "normal", "uniform"]
  fully_connected_layers:
    - [256, 128]
    - [512, 256, 128]
  activation_fc: ["relu", "tanh", "prelu", "gelu", "swish"]

training:
  gradient_clipping:
    enabled: [true, false]
    min: 0.1
    max: 3.0

  optimizer:
    type: ["adam", "sgd", "rmsprop"]
    learning_rate:
      min: 0.0001
      max: 0.01
    momentum:
      min: 0.0
      max: 0.99
    weight_decay:
      min: 0.00001
      max: 0.001
    weight_decay_on_bias: [true, false]

  scheduler:
    type: ["step", "reduce_on_plateau", "cosine"]
    lr_decay_factor:
      min: 0.1
      max: 0.9
    step_size: [3, 5, 8]

  loss_function:
    type: ["cross_entropy", "focal", "dice", "tversky", "combined"]
    gamma:
      min: 1.0
      max: 5.0
    alpha:
      min: 0.25
      max: 1.0

regularization:
  l1:
    enabled: [true, false]
    strength:
      min: 0.00001
      max: 0.001
  l2:
    enabled: [true, false]
    strength:
      min: 0.00001
      max: 0.001
  dropout:
    enabled: [true, false]
    position: ["after_conv", "after_activation", "after_fc"]
    rate:
      min: 0.1
      max: 0.5
  dropconnect:
    enabled: [true, false]
    rate:
      min: 0.1
      max: 0.5

augmentation:
  brightness:
    enabled: [true, false]
    min: 0
    max: 0.5
  contrast:
    enabled: [true, false]
    min: 0
    max: 0.5
  rotation:
    enabled: [true, false]
  crop:
    enabled: [true, false]
    size:
      min: 100
      max: 128
